name: shadowdriverjs-beta-package-release
on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - uses: action/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - name: Prepare package or dist folder
        run: |
          # ensure package.json is in the package or dist folder has required info
          cp package.json package/
          cp README.md package/
          cp LICENSE package/
          # copying the shadowReporter templates
          cp src/shadowReporter/template.html
          # cp pakcage.json dist/
          # cp README.md dist/
          # cp LICENSE dist/
          #cp src/shadowReporter/template.html
        - name: verify dist or package contents
          run: ls -la package
    publish-npm:
      needs: build
      runs-on: ubuntu-latest
        steps:
          - uses: action/checkout@v4
          - uses: action/setup-node@v3
            with:
              node-version: 16
              registry-url: https://registry.npmjs.org/
          - name: Intall dep
            run: npm ci
          - name: Publish packages
            working-directory: package
            run: npm publish
            env:
              NODE_AUTH_TOKEN: ${{secrets.REPO_SHADOWDRIVERJS_NIT_TOKEN}}